interface EmojiEntry { e: string; k: string }
interface EmojiCatDef { key: string; label: string; icon: string; items: EmojiEntry[] }

const FREQUENT: EmojiEntry[] = [
  { e: '❤️', k: 'heart love red' },
  { e: '😂', k: 'laugh cry funny tears joy' },
  { e: '👍', k: 'thumbs up like good yes approve' },
  { e: '😮', k: 'wow surprised open mouth' },
  { e: '😢', k: 'cry sad tear' },
  { e: '🎉', k: 'party celebrate confetti popper' },
  { e: '🔥', k: 'fire hot flame lit' },
  { e: '👏', k: 'clap applause' },
  { e: '😍', k: 'love heart eyes' },
  { e: '🙏', k: 'pray thank please hands' },
  { e: '✨', k: 'sparkle stars shine' },
  { e: '💯', k: 'hundred perfect score' },
  { e: '😊', k: 'smile happy blush' },
  { e: '🥰', k: 'love hearts smiling' },
  { e: '😎', k: 'cool sunglasses' },
  { e: '🤣', k: 'rofl laugh rolling funny floor' },
  { e: '💪', k: 'strong muscle flex arm' },
  { e: '🎊', k: 'confetti celebrate party' },
  { e: '🌟', k: 'glowing star' },
  { e: '💕', k: 'two hearts love' },
];

const SMILEYS: EmojiEntry[] = [
  { e: '😀', k: 'grinning happy smile face' },
  { e: '😃', k: 'happy smile big grin' },
  { e: '😄', k: 'happy smile laugh eyes' },
  { e: '😁', k: 'grin smile beaming' },
  { e: '😆', k: 'laugh funny smile squint' },
  { e: '😅', k: 'sweat smile nervous relief' },
  { e: '😂', k: 'laugh cry funny tears joy' },
  { e: '🤣', k: 'rofl laugh rolling funny floor' },
  { e: '🙂', k: 'slight smile' },
  { e: '🙃', k: 'upside down silly sarcasm' },
  { e: '😉', k: 'wink' },
  { e: '😊', k: 'smile happy blush' },
  { e: '😇', k: 'angel halo good innocent' },
  { e: '🥰', k: 'love hearts smiling' },
  { e: '😍', k: 'love heart eyes' },
  { e: '🤩', k: 'star eyes amazing wow starstruck' },
  { e: '😘', k: 'kiss love blow' },
  { e: '😗', k: 'kiss whistle' },
  { e: '☺️', k: 'smile relaxed blush' },
  { e: '😚', k: 'kiss love closed eyes' },
  { e: '😙', k: 'kiss smile' },
  { e: '🥲', k: 'smile tear happy cry' },
  { e: '😋', k: 'yummy food delicious tongue' },
  { e: '😛', k: 'tongue silly' },
  { e: '😜', k: 'wink tongue silly' },
  { e: '🤪', k: 'crazy zany goofy' },
  { e: '😝', k: 'tongue closed eyes silly' },
  { e: '🤑', k: 'money rich greedy' },
  { e: '🤗', k: 'hug hugging happy' },
  { e: '🤭', k: 'oops hand mouth giggle' },
  { e: '🫢', k: 'gasp shock hand over mouth' },
  { e: '🫡', k: 'salute respect ok' },
  { e: '🤫', k: 'shh quiet secret' },
  { e: '🤔', k: 'thinking hmm wonder' },
  { e: '🫠', k: 'melting hot embarrassed' },
  { e: '🤐', k: 'zipper mouth quiet secret' },
  { e: '🤨', k: 'suspicious raised eyebrow skeptical' },
  { e: '😐', k: 'neutral expressionless' },
  { e: '😑', k: 'expressionless blank' },
  { e: '😶', k: 'no mouth silent' },
  { e: '🫥', k: 'invisible dotted face' },
  { e: '😏', k: 'smirk sly' },
  { e: '😒', k: 'unamused annoyed' },
  { e: '🙄', k: 'eye roll whatever' },
  { e: '😬', k: 'grimace nervous awkward' },
  { e: '🤥', k: 'lying pinocchio nose' },
  { e: '😌', k: 'relieved content calm' },
  { e: '😔', k: 'pensive sad' },
  { e: '😪', k: 'sleepy tired' },
  { e: '🤤', k: 'drooling hungry' },
  { e: '😴', k: 'sleep zzz' },
  { e: '😷', k: 'mask sick doctor' },
  { e: '🤒', k: 'sick thermometer' },
  { e: '🤕', k: 'hurt injured head bandage' },
  { e: '🤢', k: 'nausea sick gross' },
  { e: '🤮', k: 'vomit sick throw up' },
  { e: '🤧', k: 'sneeze sick tissue' },
  { e: '🥵', k: 'hot heat sweating' },
  { e: '🥶', k: 'cold freezing' },
  { e: '🥴', k: 'woozy dizzy drunk' },
  { e: '😵', k: 'dizzy spiral knocked out' },
  { e: '😵‍💫', k: 'dizzy spiral confused' },
  { e: '🤯', k: 'exploding head mind blown shocked' },
  { e: '🤠', k: 'cowboy hat western' },
  { e: '🥳', k: 'party celebration birthday hat' },
  { e: '🥸', k: 'disguise glasses mustache' },
  { e: '😎', k: 'cool sunglasses' },
  { e: '🤓', k: 'nerd glasses' },
  { e: '🧐', k: 'monocle inspect curious' },
  { e: '😕', k: 'confused' },
  { e: '🫤', k: 'confused diagonal mouth' },
  { e: '😟', k: 'worried' },
  { e: '🙁', k: 'frown sad slight' },
  { e: '☹️', k: 'frown sad' },
  { e: '😮', k: 'wow surprised open mouth' },
  { e: '😯', k: 'stunned surprised' },
  { e: '😲', k: 'astonished shocked' },
  { e: '😳', k: 'flushed embarrassed blush surprised' },
  { e: '🥺', k: 'pleading puppy eyes please' },
  { e: '🥹', k: 'holding back tears touched' },
  { e: '😦', k: 'frowning open mouth' },
  { e: '😧', k: 'anguished' },
  { e: '😨', k: 'fearful scared' },
  { e: '😰', k: 'anxious nervous sweat' },
  { e: '😥', k: 'sad relieved disappointed' },
  { e: '😢', k: 'cry sad tear' },
  { e: '😭', k: 'cry sob sad tears' },
  { e: '😱', k: 'shocked scared scream gasp' },
  { e: '😖', k: 'confounded frustrated' },
  { e: '😣', k: 'persevere struggling' },
  { e: '😞', k: 'disappointed sad' },
  { e: '😓', k: 'downcast sweat' },
  { e: '😩', k: 'weary tired exhausted' },
  { e: '😫', k: 'tired exhausted frustrated' },
  { e: '🥱', k: 'yawn tired bored' },
  { e: '😤', k: 'triumphant angry steam' },
  { e: '😡', k: 'angry mad red face' },
  { e: '😠', k: 'angry mad' },
  { e: '🤬', k: 'curse swear angry symbols' },
  { e: '😈', k: 'devil evil purple horns smirk' },
  { e: '👿', k: 'angry devil red horns' },
  { e: '💀', k: 'skull death dead' },
  { e: '☠️', k: 'skull crossbones death poison' },
  { e: '💩', k: 'poop poo funny' },
  { e: '🤡', k: 'clown' },
  { e: '👹', k: 'ogre monster' },
  { e: '👺', k: 'goblin monster' },
  { e: '👻', k: 'ghost boo halloween' },
  { e: '👽', k: 'alien extraterrestrial ufo' },
  { e: '👾', k: 'alien monster space game invader' },
  { e: '🤖', k: 'robot machine bot' },
  { e: '😺', k: 'cat smile happy' },
  { e: '😸', k: 'cat grin happy' },
  { e: '😹', k: 'cat laugh tears joy' },
  { e: '😻', k: 'cat heart eyes love' },
  { e: '😼', k: 'cat smirk' },
  { e: '😽', k: 'cat kiss' },
  { e: '🙀', k: 'cat scream weary shocked' },
  { e: '😿', k: 'cat cry sad' },
  { e: '😾', k: 'cat pouting angry' },
];

const GESTURES: EmojiEntry[] = [
  { e: '👋', k: 'wave hello hi bye hand' },
  { e: '🤚', k: 'raised back of hand stop' },
  { e: '🖐️', k: 'hand raised five fingers stop' },
  { e: '✋', k: 'stop hand raised high five' },
  { e: '🖖', k: 'vulcan salute spock' },
  { e: '🫱', k: 'rightwards hand' },
  { e: '🫲', k: 'leftwards hand' },
  { e: '🫳', k: 'palm down hand' },
  { e: '🫴', k: 'palm up hand offer' },
  { e: '👌', k: 'ok perfect' },
  { e: '🤌', k: 'pinched fingers italian' },
  { e: '🤏', k: 'pinch small tiny bit' },
  { e: '✌️', k: 'peace victory two fingers' },
  { e: '🤞', k: 'fingers crossed luck hope' },
  { e: '🫰', k: 'snap fingers heart' },
  { e: '🤟', k: 'love you hand sign' },
  { e: '🤘', k: 'rock metal horns' },
  { e: '🤙', k: 'call me shaka hang loose' },
  { e: '👈', k: 'point left' },
  { e: '👉', k: 'point right' },
  { e: '👆', k: 'point up' },
  { e: '🖕', k: 'middle finger rude' },
  { e: '👇', k: 'point down' },
  { e: '☝️', k: 'point up index one' },
  { e: '🫵', k: 'point at you' },
  { e: '👍', k: 'thumbs up like good yes approve' },
  { e: '👎', k: 'thumbs down dislike bad no' },
  { e: '✊', k: 'raised fist power' },
  { e: '👊', k: 'punch fist bump' },
  { e: '🤛', k: 'left fist bump' },
  { e: '🤜', k: 'right fist bump' },
  { e: '👏', k: 'clap applause' },
  { e: '🙌', k: 'celebrate hands up raise praise' },
  { e: '🫶', k: 'heart hands love' },
  { e: '👐', k: 'open hands hug' },
  { e: '🤲', k: 'palms up together pray' },
  { e: '🤝', k: 'handshake deal agree' },
  { e: '🙏', k: 'pray thank please hands' },
  { e: '✍️', k: 'writing hand' },
  { e: '💅', k: 'nail polish sassy done' },
  { e: '🤳', k: 'selfie phone' },
  { e: '💪', k: 'strong muscle flex arm' },
  { e: '🦾', k: 'mechanical arm strong prosthetic' },
];

const PEOPLE: EmojiEntry[] = [
  { e: '👶', k: 'baby' },
  { e: '🧒', k: 'child kid' },
  { e: '👦', k: 'boy' },
  { e: '👧', k: 'girl' },
  { e: '🧑', k: 'person adult' },
  { e: '👱', k: 'blonde hair person' },
  { e: '👨', k: 'man' },
  { e: '🧔', k: 'beard person' },
  { e: '👩', k: 'woman' },
  { e: '🧓', k: 'older person' },
  { e: '👴', k: 'old man grandpa' },
  { e: '👵', k: 'old woman grandma' },
  { e: '🙍', k: 'frowning person' },
  { e: '🙎', k: 'pouting person' },
  { e: '🙅', k: 'no gesturing person stop' },
  { e: '🙆', k: 'ok gesturing person' },
  { e: '💁', k: 'information desk person tip' },
  { e: '🙋', k: 'raising hand person' },
  { e: '🧏', k: 'deaf person' },
  { e: '🙇', k: 'bowing person apology' },
  { e: '🤦', k: 'facepalm person' },
  { e: '🤷', k: 'shrug person dont know' },
  { e: '👮', k: 'police officer cop' },
  { e: '🕵️', k: 'detective spy' },
  { e: '💂', k: 'guard' },
  { e: '🥷', k: 'ninja' },
  { e: '👷', k: 'construction worker builder' },
  { e: '🫅', k: 'person crown royalty' },
  { e: '🤴', k: 'prince' },
  { e: '👸', k: 'princess' },
  { e: '👳', k: 'turban person' },
  { e: '👲', k: 'skullcap person' },
  { e: '🧕', k: 'headscarf hijab person' },
  { e: '🤵', k: 'tuxedo person groom' },
  { e: '👰', k: 'veil bride person' },
  { e: '🤰', k: 'pregnant person' },
  { e: '🤱', k: 'breastfeeding nursing' },
  { e: '👼', k: 'baby angel' },
  { e: '🎅', k: 'santa claus christmas' },
  { e: '🤶', k: 'mrs claus christmas' },
  { e: '🦸', k: 'superhero' },
  { e: '🦹', k: 'supervillain' },
  { e: '🧙', k: 'mage wizard witch' },
  { e: '🧚', k: 'fairy' },
  { e: '🧛', k: 'vampire' },
  { e: '🧜', k: 'mermaid merman' },
  { e: '🧝', k: 'elf' },
  { e: '🧞', k: 'genie' },
  { e: '🧟', k: 'zombie' },
  { e: '💆', k: 'massage relax spa' },
  { e: '💇', k: 'haircut salon' },
  { e: '🚶', k: 'walking person' },
  { e: '🧍', k: 'standing person' },
  { e: '🧎', k: 'kneeling person' },
  { e: '🏃', k: 'running person' },
  { e: '💃', k: 'dancing woman salsa' },
  { e: '🕺', k: 'dancing man' },
  { e: '👯', k: 'bunny ears dancers party' },
  { e: '🧖', k: 'sauna steam room' },
  { e: '👭', k: 'women holding hands' },
  { e: '👫', k: 'couple holding hands' },
  { e: '👬', k: 'men holding hands' },
  { e: '💏', k: 'kiss couple' },
  { e: '💑', k: 'couple heart love' },
  { e: '👪', k: 'family' },
  { e: '🗣️', k: 'speaking head talk' },
  { e: '👤', k: 'silhouette person bust' },
  { e: '👥', k: 'silhouettes people group' },
  { e: '🫂', k: 'hug people' },
];

const ANIMALS: EmojiEntry[] = [
  { e: '🐶', k: 'dog puppy pet' },
  { e: '🐱', k: 'cat kitten pet' },
  { e: '🐭', k: 'mouse rodent' },
  { e: '🐹', k: 'hamster' },
  { e: '🐰', k: 'rabbit bunny ears' },
  { e: '🦊', k: 'fox' },
  { e: '🐻', k: 'bear' },
  { e: '🐼', k: 'panda bear' },
  { e: '🐨', k: 'koala' },
  { e: '🐯', k: 'tiger' },
  { e: '🦁', k: 'lion king' },
  { e: '🐮', k: 'cow moo' },
  { e: '🐷', k: 'pig oink' },
  { e: '🐽', k: 'pig nose' },
  { e: '🐸', k: 'frog' },
  { e: '🐵', k: 'monkey' },
  { e: '🙈', k: 'see no evil monkey' },
  { e: '🙉', k: 'hear no evil monkey' },
  { e: '🙊', k: 'speak no evil monkey' },
  { e: '🐒', k: 'monkey' },
  { e: '🐔', k: 'chicken hen' },
  { e: '🐧', k: 'penguin' },
  { e: '🐦', k: 'bird' },
  { e: '🐤', k: 'chick baby bird' },
  { e: '🦆', k: 'duck' },
  { e: '🦅', k: 'eagle hawk' },
  { e: '🦉', k: 'owl' },
  { e: '🦇', k: 'bat halloween' },
  { e: '🐺', k: 'wolf' },
  { e: '🐗', k: 'boar' },
  { e: '🐴', k: 'horse' },
  { e: '🦄', k: 'unicorn rainbow' },
  { e: '🐝', k: 'bee honey bug' },
  { e: '🪱', k: 'worm' },
  { e: '🐛', k: 'caterpillar bug' },
  { e: '🦋', k: 'butterfly' },
  { e: '🐌', k: 'snail slow' },
  { e: '🐞', k: 'ladybug bug' },
  { e: '🐜', k: 'ant bug' },
  { e: '🪰', k: 'fly bug' },
  { e: '🕷️', k: 'spider' },
  { e: '🦂', k: 'scorpion' },
  { e: '🐢', k: 'turtle slow' },
  { e: '🐍', k: 'snake' },
  { e: '🦎', k: 'lizard' },
  { e: '🦖', k: 'trex dinosaur' },
  { e: '🦕', k: 'dinosaur sauropod' },
  { e: '🐙', k: 'octopus' },
  { e: '🦑', k: 'squid' },
  { e: '🦐', k: 'shrimp' },
  { e: '🦀', k: 'crab' },
  { e: '🐡', k: 'pufferfish blowfish' },
  { e: '🐠', k: 'tropical fish' },
  { e: '🐟', k: 'fish' },
  { e: '🐬', k: 'dolphin' },
  { e: '🐳', k: 'whale spouting' },
  { e: '🐋', k: 'whale' },
  { e: '🦈', k: 'shark' },
  { e: '🐊', k: 'crocodile alligator' },
  { e: '🐆', k: 'leopard' },
  { e: '🦓', k: 'zebra' },
  { e: '🦍', k: 'gorilla' },
  { e: '🦧', k: 'orangutan' },
  { e: '🐘', k: 'elephant' },
  { e: '🦣', k: 'mammoth' },
  { e: '🦒', k: 'giraffe' },
  { e: '🦘', k: 'kangaroo' },
  { e: '🐄', k: 'cow' },
  { e: '🐎', k: 'racehorse' },
  { e: '🐖', k: 'pig' },
  { e: '🐏', k: 'ram sheep' },
  { e: '🐑', k: 'sheep ewe' },
  { e: '🦙', k: 'llama alpaca' },
  { e: '🐐', k: 'goat' },
  { e: '🦌', k: 'deer' },
  { e: '🐕', k: 'dog' },
  { e: '🐩', k: 'poodle dog' },
  { e: '🐈', k: 'cat' },
  { e: '🐓', k: 'rooster' },
  { e: '🦃', k: 'turkey thanksgiving' },
  { e: '🦤', k: 'dodo' },
  { e: '🦚', k: 'peacock' },
  { e: '🦜', k: 'parrot' },
  { e: '🦢', k: 'swan' },
  { e: '🕊️', k: 'dove peace' },
  { e: '🐇', k: 'rabbit' },
  { e: '🦝', k: 'raccoon' },
  { e: '🦨', k: 'skunk' },
  { e: '🦡', k: 'badger' },
  { e: '🦫', k: 'beaver' },
  { e: '🦦', k: 'otter' },
  { e: '🦥', k: 'sloth slow' },
  { e: '🐁', k: 'mouse' },
  { e: '🐿️', k: 'chipmunk squirrel' },
  { e: '🦔', k: 'hedgehog' },
  { e: '🐾', k: 'paw prints animal tracks' },
];

const NATURE: EmojiEntry[] = [
  { e: '🌵', k: 'cactus desert' },
  { e: '🎄', k: 'christmas tree' },
  { e: '🌲', k: 'evergreen tree' },
  { e: '🌳', k: 'deciduous tree' },
  { e: '🌴', k: 'palm tree tropical' },
  { e: '🪴', k: 'potted plant' },
  { e: '🌱', k: 'seedling sprout plant' },
  { e: '🌿', k: 'herb leaf' },
  { e: '☘️', k: 'shamrock clover' },
  { e: '🍀', k: 'four leaf clover luck' },
  { e: '🎍', k: 'pine decoration' },
  { e: '🪵', k: 'wood log' },
  { e: '🌾', k: 'sheaf rice grain' },
  { e: '🌷', k: 'tulip flower' },
  { e: '🌹', k: 'rose flower red love' },
  { e: '🥀', k: 'wilted flower' },
  { e: '🌺', k: 'flower hibiscus' },
  { e: '🌸', k: 'cherry blossom flower spring' },
  { e: '🌼', k: 'blossom flower daisy' },
  { e: '🌻', k: 'sunflower' },
  { e: '🌞', k: 'sun face bright' },
  { e: '🌝', k: 'full moon face' },
  { e: '🌛', k: 'moon face' },
  { e: '🌜', k: 'moon face' },
  { e: '🌚', k: 'new moon face' },
  { e: '🌕', k: 'full moon' },
  { e: '🌖', k: 'waning moon' },
  { e: '🌗', k: 'half moon' },
  { e: '🌘', k: 'waning crescent moon' },
  { e: '🌑', k: 'new moon' },
  { e: '🌒', k: 'waxing crescent moon' },
  { e: '🌓', k: 'half moon' },
  { e: '🌔', k: 'waxing moon' },
  { e: '🌙', k: 'crescent moon night' },
  { e: '🌎', k: 'earth globe world americas' },
  { e: '🌍', k: 'earth globe world africa europe' },
  { e: '🌏', k: 'earth globe world asia' },
  { e: '💫', k: 'dizzy shooting star' },
  { e: '⭐', k: 'star favorite' },
  { e: '🌟', k: 'glowing star' },
  { e: '✨', k: 'sparkle stars shine' },
  { e: '⚡', k: 'lightning bolt electric fast zap' },
  { e: '☄️', k: 'comet' },
  { e: '💥', k: 'boom explosion collision' },
  { e: '🔥', k: 'fire hot flame lit' },
  { e: '🌪️', k: 'tornado twister' },
  { e: '🌈', k: 'rainbow colorful' },
  { e: '☀️', k: 'sun sunny bright weather' },
  { e: '🌤️', k: 'sun behind small cloud' },
  { e: '⛅', k: 'partly cloudy weather' },
  { e: '🌥️', k: 'sun behind large cloud' },
  { e: '☁️', k: 'cloud weather' },
  { e: '🌦️', k: 'sun behind rain cloud' },
  { e: '🌧️', k: 'rain cloud weather' },
  { e: '⛈️', k: 'thunderstorm lightning cloud' },
  { e: '🌩️', k: 'lightning cloud' },
  { e: '🌨️', k: 'snow cloud weather' },
  { e: '❄️', k: 'snowflake cold ice winter' },
  { e: '☃️', k: 'snowman' },
  { e: '⛄', k: 'snowman no snow' },
  { e: '🌬️', k: 'wind blowing face' },
  { e: '💨', k: 'dash wind fast' },
  { e: '🌊', k: 'wave ocean water' },
  { e: '💧', k: 'droplet water tear' },
  { e: '☔', k: 'umbrella rain' },
];

const FOOD: EmojiEntry[] = [
  { e: '🍎', k: 'apple red fruit' },
  { e: '🍏', k: 'green apple fruit' },
  { e: '🍐', k: 'pear fruit' },
  { e: '🍊', k: 'orange tangerine fruit' },
  { e: '🍋', k: 'lemon sour citrus' },
  { e: '🍌', k: 'banana yellow fruit' },
  { e: '🍉', k: 'watermelon' },
  { e: '🍇', k: 'grapes' },
  { e: '🍓', k: 'strawberry' },
  { e: '🫐', k: 'blueberries' },
  { e: '🍈', k: 'melon' },
  { e: '🍒', k: 'cherries' },
  { e: '🍑', k: 'peach' },
  { e: '🥭', k: 'mango' },
  { e: '🍍', k: 'pineapple' },
  { e: '🥥', k: 'coconut' },
  { e: '🥝', k: 'kiwi' },
  { e: '🍅', k: 'tomato' },
  { e: '🍆', k: 'eggplant aubergine' },
  { e: '🥑', k: 'avocado' },
  { e: '🥦', k: 'broccoli' },
  { e: '🥬', k: 'leafy green lettuce' },
  { e: '🥒', k: 'cucumber' },
  { e: '🌶️', k: 'hot pepper chili spicy' },
  { e: '🫑', k: 'bell pepper' },
  { e: '🥕', k: 'carrot' },
  { e: '🧄', k: 'garlic' },
  { e: '🧅', k: 'onion' },
  { e: '🥔', k: 'potato' },
  { e: '🍠', k: 'sweet potato' },
  { e: '🥐', k: 'croissant bread' },
  { e: '🍞', k: 'bread loaf' },
  { e: '🥖', k: 'baguette bread french' },
  { e: '🥨', k: 'pretzel' },
  { e: '🧀', k: 'cheese' },
  { e: '🥚', k: 'egg' },
  { e: '🍳', k: 'fried egg cooking' },
  { e: '🧈', k: 'butter' },
  { e: '🥞', k: 'pancakes' },
  { e: '🧇', k: 'waffle' },
  { e: '🥓', k: 'bacon' },
  { e: '🥩', k: 'steak meat' },
  { e: '🍗', k: 'chicken leg drumstick meat' },
  { e: '🍖', k: 'meat bone' },
  { e: '🌭', k: 'hot dog' },
  { e: '🍔', k: 'burger hamburger' },
  { e: '🍟', k: 'french fries chips' },
  { e: '🍕', k: 'pizza' },
  { e: '🫓', k: 'flatbread pita' },
  { e: '🥪', k: 'sandwich' },
  { e: '🌮', k: 'taco' },
  { e: '🌯', k: 'burrito wrap' },
  { e: '🫔', k: 'tamale' },
  { e: '🥙', k: 'stuffed flatbread gyro' },
  { e: '🧆', k: 'falafel' },
  { e: '🥗', k: 'salad greens' },
  { e: '🍿', k: 'popcorn movie' },
  { e: '🧈', k: 'butter' },
  { e: '🧂', k: 'salt' },
  { e: '🥫', k: 'canned food' },
  { e: '🍱', k: 'bento box lunch' },
  { e: '🍘', k: 'rice cracker' },
  { e: '🍙', k: 'rice ball onigiri' },
  { e: '🍚', k: 'rice bowl' },
  { e: '🍛', k: 'curry rice' },
  { e: '🍜', k: 'noodles ramen' },
  { e: '🍝', k: 'spaghetti pasta' },
  { e: '🍠', k: 'sweet potato' },
  { e: '🍢', k: 'oden skewer' },
  { e: '🍣', k: 'sushi' },
  { e: '🍤', k: 'fried shrimp tempura' },
  { e: '🍥', k: 'fish cake narutomaki' },
  { e: '🥮', k: 'moon cake' },
  { e: '🍡', k: 'dango dessert skewer' },
  { e: '🥟', k: 'dumpling' },
  { e: '🥠', k: 'fortune cookie' },
  { e: '🥡', k: 'takeout box' },
  { e: '🦀', k: 'crab' },
  { e: '🍦', k: 'soft serve ice cream' },
  { e: '🍧', k: 'shaved ice dessert' },
  { e: '🍨', k: 'ice cream dessert' },
  { e: '🍩', k: 'donut doughnut' },
  { e: '🍪', k: 'cookie' },
  { e: '🎂', k: 'birthday cake' },
  { e: '🍰', k: 'cake slice birthday' },
  { e: '🧁', k: 'cupcake' },
  { e: '🥧', k: 'pie' },
  { e: '🍫', k: 'chocolate bar' },
  { e: '🍬', k: 'candy sweet' },
  { e: '🍭', k: 'lollipop candy' },
  { e: '🍮', k: 'custard pudding flan' },
  { e: '🍯', k: 'honey jar' },
  { e: '🍼', k: 'baby bottle milk' },
  { e: '🥛', k: 'glass of milk' },
  { e: '☕', k: 'coffee hot drink' },
  { e: '🫖', k: 'teapot' },
  { e: '🍵', k: 'tea green hot' },
  { e: '🧃', k: 'juice box' },
  { e: '🥤', k: 'cup with straw soda' },
  { e: '🧋', k: 'bubble tea boba' },
  { e: '🍶', k: 'sake bottle' },
  { e: '🍺', k: 'beer drink' },
  { e: '🍻', k: 'beers cheers clinking' },
  { e: '🥂', k: 'champagne celebration cheers glasses' },
  { e: '🍷', k: 'wine red drink' },
  { e: '🥃', k: 'whiskey spirit glass' },
  { e: '🍸', k: 'cocktail martini' },
  { e: '🍹', k: 'tropical drink juice' },
  { e: '🧉', k: 'mate drink' },
  { e: '🍾', k: 'champagne bottle pop celebrate' },
  { e: '🧊', k: 'ice cube cold' },
];

const ACTIVITY: EmojiEntry[] = [
  { e: '⚽', k: 'soccer football ball' },
  { e: '🏀', k: 'basketball ball' },
  { e: '🏈', k: 'football american ball' },
  { e: '⚾', k: 'baseball ball' },
  { e: '🥎', k: 'softball ball' },
  { e: '🎾', k: 'tennis ball' },
  { e: '🏐', k: 'volleyball ball' },
  { e: '🏉', k: 'rugby ball' },
  { e: '🎱', k: 'billiards pool eight ball' },
  { e: '🏓', k: 'ping pong table tennis' },
  { e: '🏸', k: 'badminton racket' },
  { e: '🏒', k: 'ice hockey stick' },
  { e: '🏑', k: 'field hockey stick' },
  { e: '🥍', k: 'lacrosse' },
  { e: '🏏', k: 'cricket bat' },
  { e: '⛳', k: 'golf hole flag' },
  { e: '🪁', k: 'kite' },
  { e: '🏹', k: 'bow arrow archery' },
  { e: '🎣', k: 'fishing pole' },
  { e: '🤿', k: 'diving mask snorkel' },
  { e: '🥊', k: 'boxing glove' },
  { e: '🥋', k: 'martial arts uniform karate' },
  { e: '🎽', k: 'running shirt race' },
  { e: '🛹', k: 'skateboard' },
  { e: '🛼', k: 'roller skate' },
  { e: '🛷', k: 'sled' },
  { e: '⛸️', k: 'ice skate' },
  { e: '🥌', k: 'curling stone' },
  { e: '⛷️', k: 'skiing' },
  { e: '🏂', k: 'snowboarding' },
  { e: '🪂', k: 'parachute skydiving' },
  { e: '🏋️', k: 'weight lifting gym' },
  { e: '🤼', k: 'wrestling' },
  { e: '🤸', k: 'cartwheel gymnastics' },
  { e: '⛹️', k: 'bouncing ball basketball' },
  { e: '🤺', k: 'fencing sword' },
  { e: '🏇', k: 'horse racing jockey' },
  { e: '🧘', k: 'yoga meditation lotus' },
  { e: '🏄', k: 'surfing' },
  { e: '🏊', k: 'swimming' },
  { e: '🤽', k: 'water polo' },
  { e: '🚣', k: 'rowing boat' },
  { e: '🧗', k: 'climbing' },
  { e: '🚵', k: 'mountain biking' },
  { e: '🚴', k: 'cycling bike' },
  { e: '🏆', k: 'trophy winner prize champion' },
  { e: '🥇', k: 'gold medal first place' },
  { e: '🥈', k: 'silver medal second place' },
  { e: '🥉', k: 'bronze medal third place' },
  { e: '🏅', k: 'medal sports' },
  { e: '🎖️', k: 'military medal honor' },
  { e: '🏵️', k: 'rosette' },
  { e: '🎗️', k: 'reminder ribbon awareness' },
  { e: '🎫', k: 'ticket' },
  { e: '🎟️', k: 'admission tickets' },
  { e: '🎪', k: 'circus tent' },
  { e: '🤹', k: 'juggling' },
  { e: '🎭', k: 'performing arts masks drama' },
  { e: '🩰', k: 'ballet shoes' },
  { e: '🎨', k: 'art palette paint' },
  { e: '🎬', k: 'clapper board movie film' },
  { e: '🎤', k: 'microphone sing karaoke' },
  { e: '🎧', k: 'headphones music' },
  { e: '🎼', k: 'musical score' },
  { e: '🎵', k: 'music note song' },
  { e: '🎶', k: 'music notes songs' },
  { e: '🥁', k: 'drum music' },
  { e: '🪘', k: 'drum long' },
  { e: '🎷', k: 'saxophone music' },
  { e: '🎺', k: 'trumpet music' },
  { e: '🎸', k: 'guitar music' },
  { e: '🪕', k: 'banjo music' },
  { e: '🎻', k: 'violin music' },
  { e: '🪗', k: 'accordion music' },
  { e: '🎹', k: 'piano keyboard music' },
  { e: '🎲', k: 'dice roll game' },
  { e: '♟️', k: 'chess pawn' },
  { e: '🎯', k: 'dart bullseye target' },
  { e: '🎳', k: 'bowling' },
  { e: '🎮', k: 'video game controller gaming' },
  { e: '🕹️', k: 'joystick game arcade' },
  { e: '🧩', k: 'puzzle piece jigsaw' },
];

const TRAVEL: EmojiEntry[] = [
  { e: '🗺️', k: 'world map' },
  { e: '🧭', k: 'compass direction' },
  { e: '🏔️', k: 'snow capped mountain' },
  { e: '⛰️', k: 'mountain' },
  { e: '🌋', k: 'volcano' },
  { e: '🗻', k: 'mount fuji' },
  { e: '🏕️', k: 'camping tent' },
  { e: '🏖️', k: 'beach umbrella' },
  { e: '🏜️', k: 'desert' },
  { e: '🏝️', k: 'desert island' },
  { e: '🏞️', k: 'national park' },
  { e: '🏟️', k: 'stadium' },
  { e: '🏛️', k: 'classical building museum' },
  { e: '🏗️', k: 'building construction crane' },
  { e: '🧱', k: 'brick' },
  { e: '🪨', k: 'rock stone' },
  { e: '🏘️', k: 'houses' },
  { e: '🏚️', k: 'derelict house' },
  { e: '🏠', k: 'house home' },
  { e: '🏡', k: 'house garden home' },
  { e: '🏢', k: 'office building' },
  { e: '🏣', k: 'post office japan' },
  { e: '🏤', k: 'post office european' },
  { e: '🏥', k: 'hospital' },
  { e: '🏦', k: 'bank building' },
  { e: '🏨', k: 'hotel' },
  { e: '🏩', k: 'love hotel' },
  { e: '🏪', k: 'convenience store' },
  { e: '🏫', k: 'school' },
  { e: '🏬', k: 'department store' },
  { e: '🏭', k: 'factory' },
  { e: '🏯', k: 'japanese castle' },
  { e: '🏰', k: 'castle european' },
  { e: '💒', k: 'wedding chapel' },
  { e: '🗼', k: 'tokyo tower' },
  { e: '🗽', k: 'statue of liberty' },
  { e: '⛪', k: 'church' },
  { e: '🕌', k: 'mosque' },
  { e: '🛕', k: 'hindu temple' },
  { e: '🕍', k: 'synagogue' },
  { e: '⛩️', k: 'shinto shrine' },
  { e: '🕋', k: 'kaaba mecca' },
  { e: '⛲', k: 'fountain' },
  { e: '⛺', k: 'tent camping' },
  { e: '🌁', k: 'foggy city' },
  { e: '🌃', k: 'night stars city' },
  { e: '🏙️', k: 'cityscape skyline' },
  { e: '🌄', k: 'sunrise mountains' },
  { e: '🌅', k: 'sunrise' },
  { e: '🌆', k: 'cityscape dusk' },
  { e: '🌇', k: 'sunset city' },
  { e: '🌉', k: 'bridge night' },
  { e: '♨️', k: 'hot springs' },
  { e: '🎠', k: 'carousel horse' },
  { e: '🎡', k: 'ferris wheel' },
  { e: '🎢', k: 'roller coaster' },
  { e: '💈', k: 'barber pole' },
  { e: '🎪', k: 'circus tent' },
  { e: '🚂', k: 'locomotive train' },
  { e: '🚃', k: 'railway car' },
  { e: '🚄', k: 'high speed train bullet' },
  { e: '🚅', k: 'bullet train shinkansen' },
  { e: '🚆', k: 'train' },
  { e: '🚇', k: 'metro subway' },
  { e: '🚈', k: 'light rail' },
  { e: '🚉', k: 'station train' },
  { e: '🚊', k: 'tram' },
  { e: '🚝', k: 'monorail' },
  { e: '🚞', k: 'mountain railway' },
  { e: '🚋', k: 'tram car' },
  { e: '🚌', k: 'bus' },
  { e: '🚍', k: 'oncoming bus' },
  { e: '🚎', k: 'trolleybus' },
  { e: '🚐', k: 'minibus van' },
  { e: '🚑', k: 'ambulance' },
  { e: '🚒', k: 'fire engine truck' },
  { e: '🚓', k: 'police car' },
  { e: '🚔', k: 'oncoming police car' },
  { e: '🚕', k: 'taxi cab' },
  { e: '🚖', k: 'oncoming taxi' },
  { e: '🚗', k: 'car automobile' },
  { e: '🚘', k: 'oncoming car' },
  { e: '🚙', k: 'suv car' },
  { e: '🛻', k: 'pickup truck' },
  { e: '🚚', k: 'delivery truck' },
  { e: '🚛', k: 'articulated truck' },
  { e: '🚜', k: 'tractor farm' },
  { e: '🏎️', k: 'racing car' },
  { e: '🏍️', k: 'motorcycle' },
  { e: '🛵', k: 'scooter moped' },
  { e: '🦽', k: 'manual wheelchair' },
  { e: '🦼', k: 'motorized wheelchair' },
  { e: '🛺', k: 'auto rickshaw tuk tuk' },
  { e: '🚲', k: 'bicycle bike' },
  { e: '🛴', k: 'kick scooter' },
  { e: '🚏', k: 'bus stop' },
  { e: '🛣️', k: 'motorway highway road' },
  { e: '🛤️', k: 'railway track' },
  { e: '⛽', k: 'fuel pump gas station' },
  { e: '🚨', k: 'police light siren' },
  { e: '🚥', k: 'horizontal traffic light' },
  { e: '🚦', k: 'vertical traffic light' },
  { e: '🛑', k: 'stop sign' },
  { e: '⛵', k: 'sailboat' },
  { e: '🛶', k: 'canoe kayak' },
  { e: '🚤', k: 'speedboat' },
  { e: '🛥️', k: 'motor boat' },
  { e: '🛳️', k: 'passenger ship cruise' },
  { e: '⛴️', k: 'ferry' },
  { e: '🚢', k: 'ship' },
  { e: '⚓', k: 'anchor ship' },
  { e: '🛟', k: 'ring buoy life preserver' },
  { e: '✈️', k: 'airplane fly travel' },
  { e: '🛩️', k: 'small airplane' },
  { e: '🛫', k: 'airplane departure takeoff' },
  { e: '🛬', k: 'airplane arrival landing' },
  { e: '🪂', k: 'parachute' },
  { e: '💺', k: 'seat airplane' },
  { e: '🚁', k: 'helicopter' },
  { e: '🚟', k: 'suspension railway' },
  { e: '🚠', k: 'cable car mountain' },
  { e: '🚡', k: 'aerial tramway' },
  { e: '🛰️', k: 'satellite space' },
  { e: '🚀', k: 'rocket launch space' },
  { e: '🛸', k: 'flying saucer ufo' },
  { e: '🎈', k: 'balloon party' },
  { e: '🧳', k: 'luggage suitcase travel' },
];

const OBJECTS: EmojiEntry[] = [
  { e: '📱', k: 'phone mobile cell' },
  { e: '💻', k: 'laptop computer notebook' },
  { e: '⌨️', k: 'keyboard' },
  { e: '🖥️', k: 'desktop computer' },
  { e: '🖨️', k: 'printer' },
  { e: '🖱️', k: 'computer mouse' },
  { e: '🖲️', k: 'trackball' },
  { e: '💽', k: 'computer disk' },
  { e: '💾', k: 'floppy disk save' },
  { e: '💿', k: 'optical disk cd' },
  { e: '📀', k: 'dvd' },
  { e: '📷', k: 'camera photo picture' },
  { e: '📸', k: 'camera flash photo' },
  { e: '📹', k: 'video camera' },
  { e: '🎥', k: 'movie camera film' },
  { e: '📺', k: 'television tv' },
  { e: '📻', k: 'radio' },
  { e: '📞', k: 'telephone receiver call' },
  { e: '☎️', k: 'telephone phone call' },
  { e: '📟', k: 'pager' },
  { e: '📠', k: 'fax machine' },
  { e: '🔋', k: 'battery' },
  { e: '🪫', k: 'low battery' },
  { e: '🔌', k: 'electric plug' },
  { e: '💡', k: 'light bulb idea' },
  { e: '🔦', k: 'flashlight torch' },
  { e: '🕯️', k: 'candle light' },
  { e: '🪔', k: 'diya lamp' },
  { e: '🧯', k: 'fire extinguisher' },
  { e: '🛢️', k: 'oil drum' },
  { e: '💸', k: 'money flying dollar' },
  { e: '💵', k: 'dollar banknote money' },
  { e: '💴', k: 'yen banknote money' },
  { e: '💶', k: 'euro banknote money' },
  { e: '💷', k: 'pound banknote money' },
  { e: '🪙', k: 'coin money' },
  { e: '💰', k: 'money bag' },
  { e: '💳', k: 'credit card' },
  { e: '🧾', k: 'receipt' },
  { e: '📈', k: 'chart increasing trend growth' },
  { e: '📉', k: 'chart decreasing trend loss' },
  { e: '📊', k: 'bar chart graph' },
  { e: '📋', k: 'clipboard' },
  { e: '📌', k: 'pushpin' },
  { e: '📍', k: 'round pushpin location' },
  { e: '📎', k: 'paperclip' },
  { e: '🖇️', k: 'linked paperclips' },
  { e: '📏', k: 'straight ruler' },
  { e: '📐', k: 'triangular ruler' },
  { e: '✂️', k: 'scissors cut' },
  { e: '🗃️', k: 'card file box' },
  { e: '🗄️', k: 'file cabinet' },
  { e: '🗑️', k: 'wastebasket trash delete' },
  { e: '🔒', k: 'lock secure privacy closed' },
  { e: '🔓', k: 'unlock open' },
  { e: '🔏', k: 'lock with pen' },
  { e: '🔐', k: 'lock with key secure' },
  { e: '🔑', k: 'key unlock' },
  { e: '🗝️', k: 'old key' },
  { e: '🔨', k: 'hammer tool' },
  { e: '🪓', k: 'axe' },
  { e: '⛏️', k: 'pick tool mining' },
  { e: '⚒️', k: 'hammer and pick tools' },
  { e: '🛠️', k: 'hammer and wrench tools' },
  { e: '🗡️', k: 'dagger sword' },
  { e: '⚔️', k: 'crossed swords' },
  { e: '🔫', k: 'water gun toy' },
  { e: '🪃', k: 'boomerang' },
  { e: '🏹', k: 'bow arrow' },
  { e: '🛡️', k: 'shield protect' },
  { e: '🪚', k: 'saw tool' },
  { e: '🔧', k: 'wrench tool' },
  { e: '🪛', k: 'screwdriver tool' },
  { e: '🔩', k: 'nut and bolt' },
  { e: '⚙️', k: 'gear settings' },
  { e: '🗜️', k: 'clamp tool' },
  { e: '⚖️', k: 'balance scale justice' },
  { e: '🦯', k: 'white cane blind' },
  { e: '🔗', k: 'link chain' },
  { e: '⛓️', k: 'chains' },
  { e: '🪝', k: 'hook' },
  { e: '🧰', k: 'toolbox' },
  { e: '🧲', k: 'magnet' },
  { e: '🪜', k: 'ladder' },
  { e: '⚗️', k: 'alembic chemistry' },
  { e: '🧪', k: 'test tube science experiment' },
  { e: '🧫', k: 'petri dish science' },
  { e: '🧬', k: 'dna genetics' },
  { e: '🔬', k: 'microscope science' },
  { e: '🔭', k: 'telescope' },
  { e: '📡', k: 'satellite dish antenna' },
  { e: '💉', k: 'syringe injection medical' },
  { e: '🩸', k: 'blood drop' },
  { e: '💊', k: 'pill medicine' },
  { e: '🩹', k: 'bandage adhesive' },
  { e: '🩺', k: 'stethoscope medical doctor' },
  { e: '🩻', k: 'xray' },
  { e: '🚪', k: 'door' },
  { e: '🛗', k: 'elevator lift' },
  { e: '🪞', k: 'mirror' },
  { e: '🪟', k: 'window' },
  { e: '🛏️', k: 'bed sleep' },
  { e: '🛋️', k: 'couch sofa lounge' },
  { e: '🪑', k: 'chair' },
  { e: '🚽', k: 'toilet' },
  { e: '🪠', k: 'plunger' },
  { e: '🚿', k: 'shower' },
  { e: '🛁', k: 'bathtub bath' },
  { e: '🪤', k: 'mouse trap' },
  { e: '🪒', k: 'razor shave' },
  { e: '🧴', k: 'lotion bottle' },
  { e: '🧷', k: 'safety pin' },
  { e: '🧹', k: 'broom clean' },
  { e: '🧺', k: 'basket laundry' },
  { e: '🧻', k: 'toilet paper roll' },
  { e: '🪣', k: 'bucket' },
  { e: '🧼', k: 'soap wash' },
  { e: '🫧', k: 'bubbles' },
  { e: '🪥', k: 'toothbrush' },
  { e: '🧽', k: 'sponge clean' },
  { e: '🧯', k: 'fire extinguisher' },
  { e: '🛒', k: 'shopping cart trolley' },
  { e: '🚬', k: 'cigarette smoking' },
  { e: '⚰️', k: 'coffin' },
  { e: '🪦', k: 'headstone grave' },
  { e: '⚱️', k: 'funeral urn' },
  { e: '🗿', k: 'moai statue' },
  { e: '🪧', k: 'placard sign protest' },
  { e: '🪪', k: 'identification card id' },
  { e: '💼', k: 'briefcase work' },
  { e: '📁', k: 'folder' },
  { e: '📂', k: 'open folder' },
  { e: '🗂️', k: 'card index dividers' },
  { e: '📅', k: 'calendar date' },
  { e: '📆', k: 'tear off calendar' },
  { e: '🗓️', k: 'spiral calendar' },
  { e: '📇', k: 'card index rolodex' },
  { e: '📈', k: 'chart increasing' },
  { e: '📒', k: 'ledger notebook' },
  { e: '📓', k: 'notebook' },
  { e: '📔', k: 'notebook decorative cover' },
  { e: '📕', k: 'closed book red' },
  { e: '📗', k: 'green book' },
  { e: '📘', k: 'blue book' },
  { e: '📙', k: 'orange book' },
  { e: '📚', k: 'books stack' },
  { e: '📖', k: 'open book reading' },
  { e: '🔖', k: 'bookmark' },
  { e: '🧷', k: 'safety pin' },
  { e: '🔗', k: 'link' },
  { e: '📎', k: 'paperclip' },
  { e: '🖊️', k: 'pen' },
  { e: '🖋️', k: 'fountain pen' },
  { e: '✒️', k: 'black nib pen' },
  { e: '🖌️', k: 'paintbrush' },
  { e: '🖍️', k: 'crayon' },
  { e: '📝', k: 'memo note writing pencil' },
  { e: '✏️', k: 'pencil write' },
  { e: '🔍', k: 'magnifying glass search left' },
  { e: '🔎', k: 'magnifying glass search right' },
  { e: '🔏', k: 'lock pen' },
  { e: '✉️', k: 'envelope email mail' },
  { e: '📧', k: 'email letter' },
  { e: '📨', k: 'incoming envelope mail' },
  { e: '📩', k: 'envelope with arrow' },
  { e: '📤', k: 'outbox tray sent' },
  { e: '📥', k: 'inbox tray received' },
  { e: '📦', k: 'package box delivery' },
  { e: '🏷️', k: 'label tag' },
  { e: '📪', k: 'closed mailbox flag down' },
  { e: '📫', k: 'closed mailbox flag up' },
  { e: '📬', k: 'open mailbox flag up' },
  { e: '📭', k: 'open mailbox flag down' },
  { e: '📮', k: 'postbox mail' },
];

const SYMBOLS: EmojiEntry[] = [
  { e: '❤️', k: 'heart love red' },
  { e: '🧡', k: 'heart orange' },
  { e: '💛', k: 'heart yellow' },
  { e: '💚', k: 'heart green' },
  { e: '💙', k: 'heart blue' },
  { e: '💜', k: 'heart purple' },
  { e: '🖤', k: 'heart black' },
  { e: '🤍', k: 'heart white' },
  { e: '🤎', k: 'heart brown' },
  { e: '💔', k: 'broken heart' },
  { e: '❤️‍🔥', k: 'heart fire love passion' },
  { e: '❤️‍🩹', k: 'heart mending healing' },
  { e: '❣️', k: 'heart exclamation' },
  { e: '💕', k: 'two hearts love' },
  { e: '💞', k: 'revolving hearts love' },
  { e: '💓', k: 'beating heart love' },
  { e: '💗', k: 'growing heart love' },
  { e: '💖', k: 'sparkling heart love' },
  { e: '💘', k: 'heart with arrow cupid' },
  { e: '💝', k: 'heart with ribbon gift' },
  { e: '💟', k: 'heart decoration' },
  { e: '☮️', k: 'peace symbol' },
  { e: '✝️', k: 'latin cross christian' },
  { e: '☪️', k: 'star and crescent islam' },
  { e: '🕉️', k: 'om hindu' },
  { e: '☸️', k: 'wheel of dharma buddhist' },
  { e: '✡️', k: 'star of david jewish' },
  { e: '🔯', k: 'six pointed star' },
  { e: '🕎', k: 'menorah jewish' },
  { e: '☯️', k: 'yin yang' },
  { e: '☦️', k: 'orthodox cross' },
  { e: '🛐', k: 'place of worship' },
  { e: '⛎', k: 'ophiuchus zodiac' },
  { e: '♈', k: 'aries zodiac' },
  { e: '♉', k: 'taurus zodiac' },
  { e: '♊', k: 'gemini zodiac' },
  { e: '♋', k: 'cancer zodiac' },
  { e: '♌', k: 'leo zodiac' },
  { e: '♍', k: 'virgo zodiac' },
  { e: '♎', k: 'libra zodiac' },
  { e: '♏', k: 'scorpio zodiac' },
  { e: '♐', k: 'sagittarius zodiac' },
  { e: '♑', k: 'capricorn zodiac' },
  { e: '♒', k: 'aquarius zodiac' },
  { e: '♓', k: 'pisces zodiac' },
  { e: '🆔', k: 'id button' },
  { e: '🆗', k: 'ok button okay' },
  { e: '🆕', k: 'new button' },
  { e: '🆒', k: 'cool button' },
  { e: '🆓', k: 'free button' },
  { e: '🆙', k: 'up button' },
  { e: '🆘', k: 'sos help button' },
  { e: '🆚', k: 'vs button versus' },
  { e: '🅰️', k: 'a button blood type' },
  { e: '🅱️', k: 'b button blood type' },
  { e: '🅾️', k: 'o button blood type' },
  { e: '🆎', k: 'ab button blood type' },
  { e: 'ℹ️', k: 'information info' },
  { e: 'Ⓜ️', k: 'm circled button' },
  { e: '🅿️', k: 'parking p button' },
  { e: '⚛️', k: 'atom symbol science' },
  { e: '♻️', k: 'recycle recycling symbol' },
  { e: '📛', k: 'name badge' },
  { e: '⚠️', k: 'warning caution danger' },
  { e: '✅', k: 'check mark done yes' },
  { e: '☑️', k: 'checked box' },
  { e: '✔️', k: 'check mark' },
  { e: '❌', k: 'cross wrong no' },
  { e: '❎', k: 'cross mark button' },
  { e: '➕', k: 'plus add' },
  { e: '➖', k: 'minus subtract' },
  { e: '➗', k: 'divide' },
  { e: '✖️', k: 'multiply times' },
  { e: '♾️', k: 'infinity' },
  { e: '‼️', k: 'double exclamation mark' },
  { e: '⁉️', k: 'exclamation question mark' },
  { e: '❓', k: 'question mark' },
  { e: '❔', k: 'white question mark' },
  { e: '❕', k: 'white exclamation mark' },
  { e: '❗', k: 'exclamation mark' },
  { e: '🔞', k: 'no one under eighteen' },
  { e: '📵', k: 'no mobile phones' },
  { e: '🚫', k: 'prohibited no entry' },
  { e: '🔰', k: 'beginner japanese symbol' },
  { e: '💯', k: 'hundred perfect score' },
  { e: '💢', k: 'anger symbol' },
  { e: '💬', k: 'speech balloon chat' },
  { e: '👁️‍🗨️', k: 'eye speech bubble witness' },
  { e: '🗨️', k: 'left speech bubble' },
  { e: '🗯️', k: 'right anger bubble' },
  { e: '💭', k: 'thought balloon dream' },
  { e: '💤', k: 'zzz sleep' },
  { e: '♨️', k: 'hot springs steam' },
  { e: '🔴', k: 'red circle' },
  { e: '🟠', k: 'orange circle' },
  { e: '🟡', k: 'yellow circle' },
  { e: '🟢', k: 'green circle' },
  { e: '🔵', k: 'blue circle' },
  { e: '🟣', k: 'purple circle' },
  { e: '🟤', k: 'brown circle' },
  { e: '⚫', k: 'black circle' },
  { e: '⚪', k: 'white circle' },
  { e: '🟥', k: 'red square' },
  { e: '🟧', k: 'orange square' },
  { e: '🟨', k: 'yellow square' },
  { e: '🟩', k: 'green square' },
  { e: '🟦', k: 'blue square' },
  { e: '🟪', k: 'purple square' },
  { e: '🟫', k: 'brown square' },
  { e: '⬛', k: 'black square' },
  { e: '⬜', k: 'white square' },
  { e: '◼️', k: 'black medium square' },
  { e: '◻️', k: 'white medium square' },
  { e: '▪️', k: 'black small square' },
  { e: '▫️', k: 'white small square' },
  { e: '🔺', k: 'red triangle up' },
  { e: '🔻', k: 'red triangle down' },
  { e: '💠', k: 'diamond dot' },
  { e: '🔶', k: 'orange diamond large' },
  { e: '🔷', k: 'blue diamond large' },
  { e: '🔸', k: 'orange diamond small' },
  { e: '🔹', k: 'blue diamond small' },
  { e: '🔘', k: 'radio button' },
  { e: '🔲', k: 'black square button' },
  { e: '🔳', k: 'white square button' },
];

const FLAGS: EmojiEntry[] = [
  { e: '🏁', k: 'checkered flag racing finish' },
  { e: '🚩', k: 'triangular flag' },
  { e: '🎌', k: 'crossed flags japan' },
  { e: '🏴', k: 'black flag' },
  { e: '🏳️', k: 'white flag surrender' },
  { e: '🏳️‍🌈', k: 'rainbow flag pride' },
  { e: '🏳️‍⚧️', k: 'transgender flag' },
  { e: '🏴‍☠️', k: 'pirate flag skull' },
  { e: '🇺🇸', k: 'united states usa flag' },
  { e: '🇬🇧', k: 'united kingdom uk flag' },
  { e: '🇨🇦', k: 'canada flag' },
  { e: '🇲🇽', k: 'mexico flag' },
  { e: '🇧🇷', k: 'brazil flag' },
  { e: '🇦🇷', k: 'argentina flag' },
  { e: '🇩🇪', k: 'germany flag' },
  { e: '🇫🇷', k: 'france flag' },
  { e: '🇮🇹', k: 'italy flag' },
  { e: '🇪🇸', k: 'spain flag' },
  { e: '🇵🇹', k: 'portugal flag' },
  { e: '🇳🇱', k: 'netherlands flag' },
  { e: '🇷🇺', k: 'russia flag' },
  { e: '🇨🇳', k: 'china flag' },
  { e: '🇯🇵', k: 'japan flag' },
  { e: '🇰🇷', k: 'south korea flag' },
  { e: '🇮🇳', k: 'india flag' },
  { e: '🇦🇺', k: 'australia flag' },
  { e: '🇵🇭', k: 'philippines flag' },
  { e: '🇻🇳', k: 'vietnam flag' },
  { e: '🇹🇭', k: 'thailand flag' },
  { e: '🇮🇩', k: 'indonesia flag' },
  { e: '🇸🇦', k: 'saudi arabia flag' },
  { e: '🇦🇪', k: 'united arab emirates uae flag' },
  { e: '🇿🇦', k: 'south africa flag' },
  { e: '🇳🇬', k: 'nigeria flag' },
  { e: '🇪🇬', k: 'egypt flag' },
  { e: '🇹🇷', k: 'turkey flag' },
  { e: '🇬🇷', k: 'greece flag' },
  { e: '🇸🇪', k: 'sweden flag' },
  { e: '🇳🇴', k: 'norway flag' },
  { e: '🇵🇱', k: 'poland flag' },
  { e: '🇺🇦', k: 'ukraine flag' },
  { e: '🇮🇪', k: 'ireland flag' },
  { e: '🇨🇭', k: 'switzerland flag' },
];

const CATS: EmojiCatDef[] = [
  { key: 'frequent', label: 'Frequently Used', icon: '🕐', items: FREQUENT },
  { key: 'smileys', label: 'Smileys', icon: '😀', items: SMILEYS },
  { key: 'gestures', label: 'Gestures', icon: '👋', items: GESTURES },
  { key: 'people', label: 'People', icon: '🧑', items: PEOPLE },
  { key: 'animals', label: 'Animals', icon: '🐶', items: ANIMALS },
  { key: 'nature', label: 'Nature', icon: '🌿', items: NATURE },
  { key: 'food', label: 'Food', icon: '🍎', items: FOOD },
  { key: 'activity', label: 'Activities', icon: '⚽', items: ACTIVITY },
  { key: 'travel', label: 'Travel', icon: '🚀', items: TRAVEL },
  { key: 'objects', label: 'Objects', icon: '📱', items: OBJECTS },
  { key: 'symbols', label: 'Symbols', icon: '🔣', items: SYMBOLS },
  { key: 'flags', label: 'Flags', icon: '🏁', items: FLAGS },
];

export const EMOJI_CATS = CATS.map((c) => ({
  key: c.key,
  label: c.label,
  icon: c.icon,
  emojis: c.items.map((i) => i.e),
}));

export const EMOJI_SEARCH: Record<string, string> = Object.fromEntries(
  CATS.flatMap((c) => c.items.map((i) => [i.e, i.k] as const))
);
