export const EMOJI_CATS = [
  { key: 'frequent', label: 'Frequently Used', icon: '🕐', emojis: ['❤️','😂','👍','😮','😢','🎉','🔥','👏','😍','🙏','✨','💯','😊','🥰','😎','🤣','💪','🎊','🌟','💕'] },
  { key: 'smileys',  label: 'Smileys',         icon: '😀', emojis: ['😀','😃','😄','😁','😆','😅','🤣','😂','🙂','😉','😊','😇','🥰','😍','🤩','😘','😚','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤔','😐','😑','😶','😏','😒','🙄','😬','😔','😪','😴','😷','🤒','🤕','🤢','🤮','🥵','🥶','😵','🤯','🤠','🥳','😎','🤓','😭','😱','😨','😰','😥','😓','🥺','😢','😮','😲','😤','😡','🤬','😈','👿','💀','☠️','🤡','👻','👽','👾','🤖'] },
  { key: 'people',   label: 'People',          icon: '👋', emojis: ['👋','🤚','🖐️','✋','🖖','👌','✌️','🤞','🤟','🤘','👈','👉','👆','👇','☝️','👍','👎','✊','👊','👏','🙌','🤝','🙏','💪','🦾','💅','🤳','👁️','👄','👂','👃','🦷','🦴','🦵','🦶'] },
  { key: 'animals',  label: 'Animals',         icon: '🐶', emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐔','🐧','🐦','🦆','🦅','🦉','🦇','🐺','🐴','🦄','🐝','🦋','🐌','🐞','🐜','🐢','🐍','🦎','🐙','🦑','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐆','🦓','🐘','🦒','🐄','🐎','🐖','🐏','🐑','🐐','🦌','🐕','🐈','🦜','🦢','🕊️','🐇','🐁','🐿️','🦔'] },
  { key: 'food',     label: 'Food',            icon: '🍎', emojis: ['🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🥬','🥒','🌶️','🥔','🥐','🍞','🥖','🧀','🥚','🍳','🥞','🧇','🥓','🥩','🍗','🍖','🌭','🍔','🍟','🍕','🌮','🌯','🥗','🍱','🍣','🍤','🍙','🍚','🍛','🍜','🍝','🍧','🍨','🍦','🧁','🍰','🎂','🍭','🍬','🍫','🍿','🍩','🍪','☕','🍵','🧋','🍺','🍻','🥂','🍷','🥃','🍸','🍹','🍾'] },
  { key: 'activity', label: 'Activities',      icon: '⚽', emojis: ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🎱','🏓','🏸','🏒','🏑','🏏','⛳','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛷','⛸️','🥌','⛷️','🏂','🏋️','🤼','🤸','⛹️','🤺','🧘','🧗','🚵','🚴','🏆','🥇','🥈','🥉','🏅','🎖️','🎪','🎭','🎨','🎬','🎤','🎧','🎼','🎵','🎶','🎹','🥁','🎷','🎺','🎸','🎻','🎲','♟️','🎯','🎳','🎮','🕹️'] },
  { key: 'travel',   label: 'Travel',          icon: '🚀', emojis: ['🌍','🌎','🌏','🗺️','🧭','🏔️','⛰️','🌋','🏕️','🏖️','🏜️','🏝️','🏞️','🏟️','🏛️','🏘️','🏠','🏡','🏢','🏣','🏤','🏥','🏦','🏨','🏩','🏪','🏫','🏬','🏭','🏯','🏰','💒','🗼','🗽','⛪','🕌','⛩️','🕋','⛲','⛺','🌃','🌄','🌅','🌆','🌇','🌉','🌌','🌠','🎆','🎇','🚂','🚃','🚄','🚅','🚆','🚇','🚊','🚝','🚞','🚌','🚍','🚎','🚐','🚑','🚒','🚓','🚔','🚕','🚗','🚙','🛻','🚚','🚛','🚜','🏎️','🏍️','🛵','🚲','🛴','🛹','⛵','🚤','🛥️','🛳️','⛴️','🚢','✈️','🛩️','🛫','🛬','💺','🚁','🚀','🛸'] },
  { key: 'objects',  label: 'Objects',         icon: '📱', emojis: ['📱','💻','⌨️','🖥️','🖨️','🖱️','💾','💿','📀','📷','📸','📹','🎥','📺','📻','📞','☎️','📟','📠','🔋','🔌','💡','🔦','🕯️','💰','💳','📊','📈','📉','📋','📁','📂','📑','📄','📃','📜','📅','📆','📇','📒','📓','📔','📕','📗','📘','📙','📚','📖','🔖','✉️','📧','📦','🗃️','🗑️','🔒','🔓','🔑','🗝️','🔨','⚒️','🛠️','⚔️','🛡️','🔧','🔩','⚙️','🧲','💊','💉','🩺','🩹','🚪','🛏️','🛁','🧴','🧹','🧺','🧻','🪣','🧼','🧽','🧯','🛒','🚽','🚿'] },
  { key: 'symbols',  label: 'Symbols',         icon: '🔣', emojis: ['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❤️‍🔥','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🔯','✡️','♻️','⚠️','✅','❌','⭕','🛑','⛔','🚫','💯','🔞','🔰','♾️','‼️','⁉️','❓','❔','❕','❗','💤','♨️','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪','🟥','🟧','🟨','🟩','🟦','🟪','🟫','⬛','⬜','▪️','▫️'] },
];

export const EMOJI_SEARCH: Record<string, string> = {
  '❤️':'heart love red','🧡':'heart orange','💛':'heart yellow','💚':'heart green','💙':'heart blue','💜':'heart purple','🖤':'heart black','💔':'broken heart','❤️‍🔥':'heart fire love',
  '😀':'happy smile grin face','😃':'happy smile big grin','😄':'happy smile laugh','😁':'happy grin smile','😆':'laugh funny smile','😅':'sweat smile nervous','🤣':'laugh rolling funny floor','😂':'laugh cry funny tears','🙂':'slight smile','😉':'wink','😊':'smile happy blush','😇':'angel halo good','🥰':'love hearts smiling','😍':'love heart eyes','🤩':'star eyes amazing wow','😘':'kiss love blow','😚':'kiss love','😋':'yummy food delicious','😛':'tongue silly','😜':'wink tongue silly','🤪':'crazy zany','😝':'tongue closed eyes silly','🤑':'money rich greedy','🤗':'hug hugging happy','🤭':'oops hand mouth giggle','🤔':'thinking hmm wonder','😐':'neutral expressionless','😑':'expressionless blank','😶':'no mouth silent','😏':'smirk sly','😒':'unamused annoyed','🙄':'eye roll whatever','😬':'grimace nervous awkward','😔':'pensive sad','😪':'sleepy tired','😴':'sleep zzz','😷':'mask sick doctor','🤒':'sick thermometer','🤕':'hurt injured head bandage','🤢':'nausea sick vomit','🤮':'vomit sick','🥵':'hot heat sweating','🥶':'cold freezing','😵':'dizzy spiral','🤯':'exploding head mind blown','🤠':'cowboy hat western','🥳':'party celebration','😎':'cool sunglasses','🤓':'nerd glasses','😭':'cry sob sad tears','😱':'shocked scared gasp','😨':'fearful scared','😰':'anxious nervous sweat','😥':'sad relieved','😓':'downcast sweat','🥺':'pleading puppy eyes','😢':'cry sad tear','😮':'wow surprised open mouth','😲':'astonished shocked','😤':'triumphant angry steam','😡':'angry mad red face','🤬':'curse swear angry symbols','😈':'devil evil purple horns','👿':'angry devil red horns','💀':'skull death dead','☠️':'skull crossbones death','🤡':'clown','👻':'ghost boo halloween','👽':'alien extraterrestrial','👾':'alien monster space game','🤖':'robot machine',
  '👋':'wave hello hi hand','✋':'stop hand raised','🖐️':'hand raised five fingers','🖖':'vulcan salute spock','👌':'ok perfect','✌️':'peace victory two fingers','🤞':'fingers crossed luck','🤟':'love you hand','🤘':'rock metal horns','👈':'point left','👉':'point right','👆':'point up','👇':'point down','☝️':'point up index','👍':'thumbs up like good','👎':'thumbs down dislike bad','✊':'raised fist','👊':'punch fist','👏':'clap applause','🙌':'celebrate hands up raise','🤝':'handshake deal agree','🙏':'pray thank please hands','💪':'strong muscle flex arm','🦾':'mechanical arm strong',
  '🔥':'fire hot flame lit','✨':'sparkle stars shine','🎉':'party celebrate confetti popper','🎊':'confetti celebrate party','🏆':'trophy winner prize champion','⭐':'star favorite','🌟':'glowing star','💯':'hundred perfect score','🎵':'music note song','🎶':'music notes songs',
  '🐶':'dog puppy pet','🐱':'cat kitten pet','🐭':'mouse rodent','🐹':'hamster','🐰':'rabbit bunny ears','🦊':'fox','🐻':'bear','🐼':'panda bear','🐨':'koala','🐯':'tiger','🦁':'lion king','🐮':'cow moo','🐷':'pig oink','🐸':'frog','🐵':'monkey','🙈':'see no evil monkey','🙉':'hear no evil monkey','🙊':'speak no evil monkey','🐔':'chicken hen','🐧':'penguin','🐦':'bird','🦆':'duck','🦅':'eagle hawk','🦉':'owl','🦇':'bat halloween','🐴':'horse','🦄':'unicorn rainbow','🐝':'bee honey','🦋':'butterfly','🐢':'turtle slow','🐍':'snake','🐙':'octopus','🦑':'squid','🦀':'crab','🐠':'tropical fish','🐟':'fish','🐬':'dolphin','🐋':'whale','🦈':'shark',
  '🍎':'apple red fruit','🍐':'pear fruit','🍊':'orange fruit','🍋':'lemon sour citrus','🍌':'banana yellow fruit','🍉':'watermelon','🍇':'grapes','🍓':'strawberry','🍒':'cherries','🍑':'peach','🥭':'mango','🍍':'pineapple','🥥':'coconut','🥝':'kiwi','🍅':'tomato','🍆':'eggplant aubergine','🥑':'avocado','🥦':'broccoli','🥒':'cucumber','🌶️':'hot pepper chili spicy','🍕':'pizza','🍔':'burger hamburger','🍟':'french fries chips','🌭':'hot dog','🌮':'taco','🌯':'burrito wrap','🍣':'sushi','🍜':'noodles ramen','🍝':'spaghetti pasta','🧁':'cupcake','🍰':'cake slice birthday','🎂':'birthday cake','🍫':'chocolate','🍿':'popcorn movie','🍩':'donut doughnut','🍪':'cookie','☕':'coffee hot drink','🍵':'tea green hot','🧋':'bubble tea boba','🍺':'beer drink','🍻':'beers cheers clinking','🥂':'champagne celebration cheers','🍷':'wine red drink','🥃':'whiskey spirit glass','🍸':'cocktail martini','🍹':'tropical drink juice','🍾':'champagne bottle pop',
  '⚽':'soccer football ball','🏀':'basketball ball','🏈':'football american','⚾':'baseball ball','🎾':'tennis ball','🎮':'video game controller gaming','🎲':'dice roll game',
  '📱':'phone mobile cell','💻':'laptop computer notebook','📷':'camera photo picture','🔒':'lock secure privacy','🔑':'key unlock','⚠️':'warning caution danger','✅':'check mark done yes','❌':'cross wrong no',
  '🚀':'rocket launch space','✈️':'airplane fly travel','🌍':'earth globe world','🌈':'rainbow colorful','🌊':'wave ocean water','⚡':'lightning bolt electric fast','❄️':'snowflake cold ice winter','🌸':'cherry blossom flower spring','🌺':'flower hibiscus','🌹':'rose flower red love',
};
