'use client';

import * as React from 'react';
import { BarChart3, CalendarPlus, Plus, X } from 'lucide-react';
import { DateTimePicker } from '@/components/ui/datetime-picker';
import { useIsMobile } from '@/hooks/use-mobile';

export function PollModal({ onClose, onCreate }: { onClose: () => void; onCreate: (question: string, options: string[], multiple: boolean) => void }) {
  const [question, setQuestion] = React.useState('');
  const [options, setOptions] = React.useState(['', '']);
  const [multiple, setMultiple] = React.useState(false);
  const valid = question.trim() && options.filter(option => option.trim()).length >= 2;
  return <div className="ss4-overlay fixed inset-0 z-50 flex items-end justify-center p-0 sm:items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="ss4-poll-title" className="ss4-modal flex max-h-[calc(var(--ss4-vvh,100dvh)-1rem)] w-full max-w-sm flex-col overflow-hidden rounded-t-3xl sm:rounded-2xl"><div className="flex items-center justify-between px-5 py-4" style={{ borderBottom: '1px solid var(--border-1)' }}><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4" style={{ color: 'var(--accent)' }} /><h2 id="ss4-poll-title" className="ss4-display font-bold" style={{ fontSize: 16, color: 'var(--text-primary)' }}>Create Poll</h2></div><button onClick={onClose} aria-label="Close poll creator" className="ss4-icon-btn h-10 w-10"><X className="h-4 w-4" /></button></div><div className="min-h-0 space-y-3 overflow-y-auto px-4 py-4 ss4-scroll"><input value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask a question..." className="h-9 w-full rounded-lg px-3 text-sm ss4-search-input" /><div className="space-y-2">{options.map((option, index) => <div key={index} className="flex items-center gap-2"><input value={option} onChange={event => setOptions(previous => previous.map((value, optionIndex) => optionIndex === index ? event.target.value : value))} placeholder={`Option ${index + 1}`} className="h-9 flex-1 rounded-lg px-3 text-sm ss4-search-input" />{options.length > 2 && <button onClick={() => setOptions(previous => previous.filter((_, optionIndex) => optionIndex !== index))} className="ss4-icon-btn h-7 w-7"><X className="h-3.5 w-3.5" /></button>}</div>)}{options.length < 6 && <button onClick={() => setOptions(previous => [...previous, ''])} className="ss4-pill-btn flex h-8 w-full items-center justify-center gap-1.5 px-3" style={{ fontSize: 12 }}><Plus className="h-3.5 w-3.5" /> Add option</button>}</div><label className="flex cursor-pointer items-center gap-2" style={{ fontSize: 12, color: 'var(--text-secondary)' }}><input type="checkbox" checked={multiple} onChange={event => setMultiple(event.target.checked)} /> Allow multiple answers</label><button disabled={!valid} onClick={() => valid && onCreate(question.trim(), options.map(option => option.trim()).filter(Boolean), multiple)} className="ss4-send-btn h-9 w-full rounded-lg font-semibold" style={{ fontSize: 13, opacity: valid ? 1 : 0.4 }}>Create Poll</button></div></div></div>;
}

export function EventModal({ onClose, onCreate }: { onClose: () => void; onCreate: (event: { title: string; description: string; location: string; startTime: string; endTime: string }) => void }) {
  const [title, setTitle] = React.useState(''); const [description, setDescription] = React.useState(''); const [location, setLocation] = React.useState(''); const [startTime, setStartTime] = React.useState(''); const [endTime, setEndTime] = React.useState('');
  const mobilePicker = useIsMobile(); const valid = title.trim() && startTime; const dateInputClass = 'mt-1 h-9 w-full rounded-lg px-3 text-sm ss4-search-input';
  return <div className="ss4-overlay fixed inset-0 z-50 flex items-end justify-center p-0 sm:items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="ss4-event-title" className="ss4-modal flex max-h-[calc(var(--ss4-vvh,100dvh)-1rem)] w-full max-w-sm flex-col overflow-hidden rounded-t-3xl sm:rounded-2xl"><div className="flex items-center justify-between px-5 py-4" style={{ borderBottom: '1px solid var(--border-1)' }}><div className="flex items-center gap-2"><CalendarPlus className="h-4 w-4" style={{ color: 'var(--accent)' }} /><h2 id="ss4-event-title" className="ss4-display font-bold" style={{ fontSize: 16, color: 'var(--text-primary)' }}>Create Event</h2></div><button onClick={onClose} aria-label="Close event creator" className="ss4-icon-btn h-10 w-10"><X className="h-4 w-4" /></button></div><div className="min-h-0 space-y-2.5 overflow-y-auto px-4 py-4 ss4-scroll"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="Event title" className="h-9 w-full rounded-lg px-3 text-sm ss4-search-input" /><input value={location} onChange={event => setLocation(event.target.value)} placeholder="Location (optional)" className="h-9 w-full rounded-lg px-3 text-sm ss4-search-input" /><textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Description (optional)" rows={2} className="w-full resize-none rounded-lg px-3 py-2 text-sm ss4-search-input" /><div><label style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>Starts</label>{mobilePicker ? <input type="datetime-local" value={startTime} onChange={event => setStartTime(event.target.value)} className={dateInputClass} /> : <DateTimePicker value={startTime} onChange={setStartTime} placeholder="Pick start date & time" className="mt-1 h-9 text-sm" />}</div><div><label style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>Ends (optional)</label>{mobilePicker ? <input type="datetime-local" value={endTime} onChange={event => setEndTime(event.target.value)} className={dateInputClass} /> : <DateTimePicker value={endTime} onChange={setEndTime} placeholder="Pick end date & time" className="mt-1 h-9 text-sm" />}</div><button disabled={!valid} onClick={() => valid && onCreate({ title: title.trim(), description, location, startTime, endTime })} className="ss4-send-btn mt-1 h-9 w-full rounded-lg font-semibold" style={{ fontSize: 13, opacity: valid ? 1 : 0.4 }}>Create Event</button></div></div></div>;
}
