export type NotificationType =
  | 'quote_created'
  | 'quote_updated'
  | 'quote_deleted'
  | 'quote_converted'
  | 'quote_accepted'
  | 'shipment_created'
  | 'shipment_updated'
  | 'shipment_deleted'
  | 'shipment_status_changed'
  | 'shipment_assigned'
  | 'shipment_picked_up'
  | 'shipment_delivered'
  | 'proof_of_delivery'
  | 'shipment_arrived_at_pickup'
  | 'shipment_arrived_at_delivery'
  | 'vehicle_added'
  | 'vehicle_updated'
  | 'vehicle_sold'
  | 'vehicle_status_changed'
  | 'inventory_sync'
  | 'new_inventory_alert'
  | 'appointment_created'
  | 'appointment_updated'
  | 'appointment_cancelled'
  | 'appointment_reminder'
  | 'guest_response'
  | 'new_lead'
  | 'lead_assigned'
  | 'lead_status_changed'
  | 'crm_message'
  | 'crm_task_assigned'
  | 'crm_task_due'
  | 'crm_biometric'
  | 'crm_timeproof'
  | 'driver_request'
  | 'driver_request_approved'
  | 'driver_request_rejected'
  | 'driver_assigned'
  | 'driver_location_update'
  | 'driver_payout'
  | 'payment_received'
  | 'payment_pending'
  | 'payment_failed'
  | 'payment_request'
  | 'payout_processed'
  | 'team_invite_sent'
  | 'team_member_joined'
  | 'team_member_left'
  | 'role_changed'
  | 'password_changed'
  | 'email_changed'
  | 'profile_updated'
  | 'login_alert'
  | 'system_announcement'
  | 'message_received'
  | 'reminder'
  | 'general'
  | 'referral_joined'
  | 'referral_rewarded'
  | 'delivery_confirmed'
  | 'proof_submitted'
  | 'ping'
  | 'absence_approved'
  | 'absence_rejected'
  | 'board_note_posted'
  | 'aftermarket_inquiry'
  | 'aftermarket_invoice'
  | 'aftermarket_order';

export interface Notification {
  _id: string;
  userId?: string;
  organizationId?: string;
  type: NotificationType;
  title: string;
  message: string;
  metadata?: {
    quoteId?: string;
    shipmentId?: string;
    appointmentId?: string;
    vehicleId?: string;
    leadId?: string;
    driverRequestId?: string;
    paymentId?: string;
    guestEmail?: string;
    guestName?: string;
    guestPhone?: string;
    status?: string;
    previousStatus?: string;
    respondedAt?: string;
    vehicleName?: string;
    customerName?: string;
    driverName?: string;
    driverEmail?: string;
    trackingNumber?: string;
    amount?: number;
    [key: string]: any;
  };
  isRead: boolean;
  isBroadcast?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface NotificationPreferences {
  quoteCreated: boolean;
  quoteUpdated: boolean;
  quoteDeleted: boolean;
  shipmentCreated: boolean;
  shipmentUpdated: boolean;
  shipmentDeleted: boolean;
  passwordChanged: boolean;
  emailChanged: boolean;
  profileUpdated: boolean;
  loginAlerts: boolean;
  appointmentCreated: boolean;
  appointmentUpdated: boolean;
  appointmentCancelled: boolean;
  driverRequests: boolean;
  crmActivity: boolean;
  referral_joined: boolean;
  referral_rewarded: boolean;
}

export const defaultNotificationPreferences: NotificationPreferences = {
  quoteCreated: true,
  quoteUpdated: true,
  quoteDeleted: true,
  shipmentCreated: true,
  shipmentUpdated: true,
  shipmentDeleted: true,
  passwordChanged: true,
  emailChanged: true,
  profileUpdated: true,
  loginAlerts: true,
  appointmentCreated: true,
  appointmentUpdated: true,
  appointmentCancelled: true,
  driverRequests: true,
  crmActivity: true,
  referral_joined: true,
  referral_rewarded: true,
};
